name = "license-manager-lynkid"
main = "src/index.ts"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "license-manager-db"
database_id = "9c2223ee-ccbb-4517-8d80-b049a1a34cc5"
migrations_dir = "src/db/migrations"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "b333b0d597384cbd9e7b060f519bef7a"

[vars]
TURNSTILE_ENABLED = "true"
CORS_ORIGIN = "https://license-autogas.id-manager.my.id"

[triggers]
crons = ["0 0 * * *"]
